services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: threat_vision
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: threatuser
      MYSQL_PASSWORD: threatpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: